travis:
  secure:
    BINSTAR_TOKEN: NGsPg3og1wRPqAqi60r8CpSn5srBc0YIDwttVyT+mWADdubi9HNwCkmgIT4Csbn29XXtAlfr9UOsZA1Q6TVY1l3Yc9ckUNNdDIBQjfQgwBJIiwADB8izJgnyKDui8aF44NgXbpmCgPV7zdqCa62qOw1U9B/2Wegt2ocMKjaHJR2NHrS4vnJXdTc2oQTcH3IxUxlQfzDJybMlcj698bhVTtO9lQR5wMP4OCJZv2wHxvFGHy2XHbLzCq5m54ecewY6mJj6n/4h/+pH/hyB9YlReHK9Z9dAOF15OC3k9NVJLwVPkZIZcmlLHytT6593eYghH3ntAR6pUDLPKK7r7gA+Li5DSDm+z+HPTBUxZZP4tOntCUOcL1zKy9G0UkDxeRebLKOw1oCM73P3i8dPzXN61hJm3H1bkpQ1+P3AKvokXaLES4/xN+D/DNh6DYKlEhvCEekIsZUikikEbRF3890lYEab5fQRymLl8rbmYjWzHYyQyWwA/NTvWI+pgU85N8QnH91ML7VhjP+YJoVSVpen8XrsuRBobtdOd3ia/JukGWvbCTzDvGK9BRj+ToxaxlY7pCkt0JPCWe0+INw7bTZYik19kCG/NvBhxdRfMJ6yZ/lWge0GJnq7HuRCT033DvW3np8Kn3+X93kK1U7gzuJbw8DaumciXHztr52vMVauVGk=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
